version: '3.11'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
